FROM python:3.10-slim

WORKDIR /app

COPY ../requirements.txt /app/

RUN apt-get update && apt-get install -y gcc libpq-dev && \
    pip install --no-cache-dir -r requirements.txt && rm -rf /var/lib/apt/lists/*
COPY mqtt_consumer.py /app/

ENV PYTHONUNBUFFERED=1
CMD ["python","/app/mqtt_consumer.py"]