mssql:
  host: localhost 
  port: 1433
  database: master
  driver: "ODBC Driver 17 for SQL Server"

comexstat:
  base_url: "https://api-comexstat.mdic.gov.br"
  timeout: 30

logging:
  level: INFO
  file: logs/app.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_bytes: 10485760 
  